apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001 # Akses via http://<minikube_ip>:30001
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2 # Kita coba scale jadi 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never # Pake image lokal yang kita build tadi
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/orders"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
