# PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: "payments"
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5432
---
# Payment Worker (Python)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-worker
  template:
    metadata:
      labels:
        app: payment-worker
    spec:
      containers:
        - name: payment-worker
          image: payment-worker:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: POSTGRES_URI
              value: "dbname=payments user=postgres password=password host=postgres"
